// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6uIP2rpr1dZzjgM4i8e15rLxW_9t0c-w',
    appId: '1:145142242234:web:787289ca18cd5289eadb83',
    messagingSenderId: '145142242234',
    projectId: 'neuro-check-pro',
    authDomain: 'neuro-check-pro.firebaseapp.com',
    storageBucket: 'neuro-check-pro.firebasestorage.app',
    measurementId: 'G-RSY65B8MXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWMAMBeXecvOOHsqGGufwSW0aMZK1tIO4',
    appId: '1:145142242234:android:1a7db8ab50448d1aeadb83',
    messagingSenderId: '145142242234',
    projectId: 'neuro-check-pro',
    storageBucket: 'neuro-check-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1nfrX25n0F5LegEwJaFG05cV-WKXtpcg',
    appId: '1:145142242234:ios:86493b9aacd150bbeadb83',
    messagingSenderId: '145142242234',
    projectId: 'neuro-check-pro',
    storageBucket: 'neuro-check-pro.firebasestorage.app',
    androidClientId: '145142242234-ev051jenidqu380hu6oshbkspv9ri8dj.apps.googleusercontent.com',
    iosClientId: '145142242234-a8ic297fqml4dgv0rahk3oa8d41dmvq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.neuroCheckPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1nfrX25n0F5LegEwJaFG05cV-WKXtpcg',
    appId: '1:145142242234:ios:86493b9aacd150bbeadb83',
    messagingSenderId: '145142242234',
    projectId: 'neuro-check-pro',
    storageBucket: 'neuro-check-pro.firebasestorage.app',
    androidClientId: '145142242234-ev051jenidqu380hu6oshbkspv9ri8dj.apps.googleusercontent.com',
    iosClientId: '145142242234-a8ic297fqml4dgv0rahk3oa8d41dmvq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.neuroCheckPro',
  );

}