// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6uIP2rpr1dZzjgM4i8e15rLxW_9t0c-w',
    appId: '1:145142242234:web:787289ca18cd5289eadb83',
    messagingSenderId: '145142242234',
    projectId: 'neuro-check-pro',
    authDomain: 'neuro-check-pro.firebaseapp.com',
    storageBucket: 'neuro-check-pro.firebasestorage.app',
    measurementId: 'G-RSY65B8MXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlZ21jZbQNmHPVOFbkH2Aj4PLZe61_lwI',
    appId: '1:145142242234:android:5bf95029c6e83e20eadb83',
    messagingSenderId: '145142242234',
    projectId: 'neuro-check-pro',
    storageBucket: 'neuro-check-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALKb5xkQnflEMboYxX2G7hsuffwhE-R8g',
    appId: '1:145142242234:ios:e1c05249365ca308eadb83',
    messagingSenderId: '145142242234',
    projectId: 'neuro-check-pro',
    storageBucket: 'neuro-check-pro.firebasestorage.app',
    androidClientId: '145142242234-mcn4i179np03jo3t4smg6al0cpm8rt80.apps.googleusercontent.com',
    iosClientId: '145142242234-5tib0b8vnco42k0l3if7an0bntg4mphe.apps.googleusercontent.com',
    iosBundleId: 'com.neurocheckpro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALKb5xkQnflEMboYxX2G7hsuffwhE-R8g',
    appId: '1:145142242234:ios:e1c05249365ca308eadb83',
    messagingSenderId: '145142242234',
    projectId: 'neuro-check-pro',
    storageBucket: 'neuro-check-pro.firebasestorage.app',
    androidClientId: '145142242234-mcn4i179np03jo3t4smg6al0cpm8rt80.apps.googleusercontent.com',
    iosClientId: '145142242234-5tib0b8vnco42k0l3if7an0bntg4mphe.apps.googleusercontent.com',
    iosBundleId: 'com.neurocheckpro.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6uIP2rpr1dZzjgM4i8e15rLxW_9t0c-w',
    appId: '1:145142242234:web:de56e7507fe9c890eadb83',
    messagingSenderId: '145142242234',
    projectId: 'neuro-check-pro',
    authDomain: 'neuro-check-pro.firebaseapp.com',
    storageBucket: 'neuro-check-pro.firebasestorage.app',
    measurementId: 'G-XRL33JQ26R',
  );

}